name: flutter_user_agent
description: Retrieve device and webview user agent strings for Android and iOS devices.

  It also provides you with simple building blocks for generating your own user agent string.
version: 1.2.1
author: j0j00 <jojodev@protonmail.com>
homepage: https://github.com/j0j00/flutter_user_agent

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.jojodev.flutter.flutteruseragent
    pluginClass: FlutterUserAgentPlugin